description: The IRS provides this base exclusion amount under the estate tax credit. 
metadata:
  unit: currency-USD
  label: Estate tax credit base exclusion amount  
  period: year
  reference:
    - title: 26 U.S. Code ยง 2010 - Unified credit against estate tax - (c)(3)(A)
      href: https://www.law.cornell.edu/uscode/text/26/2010
values:
  2017-01-01: 5_000_000  
  2018-01-01: 10_000_000  
  2026-01-01: 5_000_000  
